import React from 'react'

function Home() {
  return (
    <div style={{padding:'30px'}}>
        <h1 style={{color:"skyblue",textAlign:"center"}}>Home Component</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quae deserunt nam excepturi voluptas accusantium, dicta cum non, accusamus iure, temporibus cupiditate autem hic dolor dignissimos nemo? Ullam voluptas, voluptatum doloremque consequuntur esse ducimus nihil? Dolore natus possimus rem voluptate quidem omnis atque mollitia nulla non odit, magnam nam corporis? Officiis recusandae quae dolores nesciunt odio ipsa velit sunt harum! Tenetur iusto inventore eum veritatis ipsam ducimus modi, necessitatibus nobis debitis repudiandae exercitationem unde atque nesciunt quae dolores. Vel, molestiae. Aliquid, illum atque! Porro, dolorum consequatur fugiat dolor sit repudiandae adipisci quas at harum dolorem hic assumenda explicabo architecto beatae numquam. Enim magnam aperiam dolores, facere molestias eius iure excepturi obcaecati repudiandae, minima numquam, cum sunt. Reprehenderit animi est placeat blanditiis culpa illo eos, dignissimos esse iure iusto eaque rerum, asperiores, vitae exercitationem itaque modi possimus ipsam consequuntur! Voluptatum expedita, mollitia voluptate recusandae odio illum eius necessitatibus saepe. Illo hic dignissimos iusto animi totam placeat, autem reiciendis quis illum, amet minus est! Obcaecati perferendis sapiente consectetur architecto nulla. Dignissimos esse unde sit dolores quidem repudiandae numquam nesciunt ratione illum repellat autem totam porro, nisi reiciendis iste voluptatibus eligendi. Distinctio rem voluptatibus, doloribus iusto quo magnam, soluta in perspiciatis facilis blanditiis earum animi quaerat, quasi corporis. Ipsam atque officia fugit suscipit sunt harum aliquid tempore alias quisquam, dolorem eum nesciunt natus tenetur eveniet nulla voluptatum obcaecati cumque. Incidunt nemo laudantium, minus necessitatibus adipisci deserunt. Ipsa autem excepturi repellat asperiores consequatur rem deserunt officiis at sunt eveniet accusantium odit quae dolorum inventore cumque vitae sapiente aperiam, ex est facilis quia vero. Alias autem adipisci ipsum. Ullam perferendis nostrum dicta iure deserunt, sapiente magnam repellendus laudantium incidunt hic autem. Deleniti eius inventore minus rem sed commodi odio delectus corrupti doloribus, consequatur fugit blanditiis alias necessitatibus culpa earum iure, ad nihil repellat a tempora natus?</p>
    </div>
  )
}

export default Home